version: '3'

services:
  app:
    container_name: test-app
    build: .

    restart: on-failure
    depends_on: 
      - redis
    environment:
      REDIS_URL: redis:6379    
    networks:
      - backend

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:    